### ISSUE TITLE
plugin google translate

### ISSUE THREAD

**Issue by klysman08** [ralosant/FlowLauncher.Google.Translator#1]
Flow Launcher version: 1.10.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/16/2022 00:06:00
Exception:
Google Translate Exception: 
Websites: https://github.com/ralosant/FlowLauncher.Google.Translator
Author: Raúl Losantos
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\klysm\AppData\Roaming\FlowLauncher\Plugins\Google Translate-1.0.0\main.py", line 17, in <module>
    from plugin.Translator import GoogTranslate
ModuleNotFoundError: No module named 'plugin'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\klysm\AppData\Roaming\FlowLauncher\Plugins\Google Translate-1.0.0\main.py", line 17, in <module>
    from plugin.Translator import GoogTranslate
ModuleNotFoundError: No module named 'plugin'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 290
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 295
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 310
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 741
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ralosant** [comment]
Could you please verify that you have three folders in that path "C:\Users\klysm\AppData\Roaming\FlowLauncher\Plugins\Google Translate-1.0.0\"? It seems that the "plugin" folder has a different name or not existing. -

**Comment by klysman08** [comment]
Hello, sorry for the delay.. I didn't see the notification.
Yaa, there are 2 folders. Imagens, Lib and some files [license, main.py, plugin, reademe.md

**Comment by ralosant** [comment]
Please try to uninstall "pm uninstall Google Translate" and reinstall using pm manager, by "pm install Google Translate". The file plugin should be a folder with another file inside.
Is weird because I can´t reproduce the issue without manual removal of the folder.

**Comment by klysman08** [comment]
It worked. I used the suggested command to uninstall and then install. Now it's working perfectly!
Thanks a lot! it's a great plugin!

**Comment by ralosant** [comment]
👍 Thanks!
